Add Ayu, Ayu-Mirage & Ayu-Dark
regolith-linux/regolith-look-extra pull request #5
Opened 2022-06-23 15:50 UTC by jjsearle

Colours are a bit different from 1.6 from looking at the old files but the new colours have been grabbed from here

https://raw.githubusercontent.com/ayu-theme/ayu-colors/master/colors.svg

### Ayu
![ayu](https://user-images.githubusercontent.com/7019630/175341196-1ff26d14-31dc-4192-8666-5cb517d6ad62.png)

### Ayu Mirage
![ayu-mirage](https://user-images.githubusercontent.com/7019630/175341193-db89a355-b7da-4dae-aff5-d078b5f68504.png)

### Ayu Dark
![ayu-dark](https://user-images.githubusercontent.com/7019630/175341188-d5d68098-cd8d-4801-8324-d471766b835d.png)

2022-06-24 02:28 UTC, kgilmer approved these changes
These look fantastic @jjsearle !  I'm happy to merge this as is.  There a few things we could do here now or perhaps in a subsequent change.

Regarding style, most of [nerdfonts](https://www.nerdfonts.com/) are packaged for Regolith (notable exception is the Noto font, it's too big).  We could give each look a more distinctive look with [different fonts](https://www.nerdfonts.com/font-downloads).  Or, if you think SourceCodePro is best I won't argue with you.

Feel free to merge or look into other fonts, your call :sun_with_face:

2022-06-24 12:53 UTC, jjsearle commented
Hey Ken - I have switched these three over to the 'Hack' font, if you are happy with this and don't want me to make any further changes please proceed with the merge. Thanks.

2022-06-26 14:50 UTC, kgilmer requested changes
The ilia CSS needs the correct font spec, otherwise LGTM

2022-06-26 14:50 UTC, kgilmer commented on usr/share/regolith-look/ayu-dark/ilia.css
> +  font-family: SauceCodePro Nerd Font;
This needs to be updated to use new font spec

2022-06-26 14:50 UTC, kgilmer commented on usr/share/regolith-look/ayu-mirage/ilia.css
> +  font-family: SauceCodePro Nerd Font;
ditto

2022-06-26 14:50 UTC, kgilmer commented on usr/share/regolith-look/ayu/ilia.css
> +  font-family: SauceCodePro Nerd Font;
same here

2022-06-26 14:57 UTC, jjsearle commented on usr/share/regolith-look/ayu/ilia.css
> +  font-family: SauceCodePro Nerd Font;
done

2022-06-26 14:58 UTC, jjsearle commented
I have corrected the ilya.css to use the new font

2022-06-26 15:01 UTC, kgilmer approved these changes
LGTM

2022-06-26 15:01 UTC, merged